### PR TITLE
Use EvalString instead of undocumented READ_COMMAND_REAL

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@laurentbartholdi ping?

**Comment by fingolfin** [comment]
@laurentbartholdi any concerns about merging this?

**Comment by laurentbartholdi** [comment]
Does this fix a problem?

If so, fine with me; but if not, I'd rather not touch any of the parsing code for fear of breaking anything -- it's really a terrible hack.

**Comment by fingolfin** [comment]
Yes, we want to remove the internal, undocumented function READ_COMMAND_REAL.

**Comment by laurentbartholdi** [comment]
OK, I did a somewhat equivalent change. (This is in a somewhat-clean part of the code, so I'm confident it won't change much). I dislike commands writing to global variables, so I used ReadAsFunction(...)() rather than EvalString.

**Pull request closed without merging**
