### PR TITLE
Don't use undocumented extra args to InstallGlobalFunction

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@laurentbartholdi did you see this second PR?

**Comment by laurentbartholdi** [comment]
Yes, I did... But I wanted to leave the extra argument as a comment.

**Comment by laurentbartholdi** [comment]
I did it differently, keeping the original message.

**Comment by fingolfin** [comment]
That's of course also fine, thanks.

**Pull request closed without merging**
