### PR TITLE
Call ClosureSubgroupNC with noassert option

### LINKED ISSUE #33: FR broken with GAP master branch
https://github.com/gap-system/gap/pull/3370 breaks FR package - see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/519813674 :
```
Syntax error: ; expected in /home/gap/inst/gap-master/pkg/fr-2.4.6/gap/cp.gi:5\
90
#%%%%%%%%%%%%%%%%%%%%	 RepresentativeActionOp %%%%%%%%%%%%%%%%%%%#
                     	                        ^
```

There is an easy fix for this - just change formatting of comments. However, it seems to me that there are other diffs, appearing a day before in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/519063953 for the first time - there was some other change in GAP master branch that triggered them.

### PR DESCRIPTION
**Pull request by alex-konovalov**
Attempt to fix #33 - do not merge yet.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
I don't quite understand what's going on. Apparently the fix is in the wrong place, since it's not covered by tests. But Travis tests pass with and without fix. But then they fail when all packages are loaded in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/573289753. What's the difference between setups here and there? But I have no time to continue this investigation now.

**Comment by wilfwilson** [comment]
@alex-konovalov Note that the diff doesn't actually use the `noassert` option. Is this deliberate?

**Comment by alex-konovalov** [comment]
@wilfwilson: yes. This has 4 commits, my plan was to test with different settings, and then rebase to throw away commits used for testing.

**Comment by laurentbartholdi** [comment]
Hi,
Is this PR an attempt to fix the "noassert" problem (which I still haven't really understood)?

No worry, I won't touch anything, promise.

**Comment by alex-konovalov** [comment]
@laurentbartholdi yes, it is. Thanks for keeping an eye on this.

**Comment by fingolfin** [comment]
@alex-konovalov how about just doing `SetAssertionLevel(1);` or `SetAssertionLevel(0);` at the start of `cp.tst`?

**Comment by alex-konovalov** [comment]
@fingolfin shouldn't this be done by START_TEST here?

https://github.com/gap-packages/fr/blob/62cd6e882821955902d11570a646af0403096298/tst/cp.tst#L6

OK, I will try.

**Comment by alex-konovalov** [comment]
Let's see. And of course `START_TEST` sets it to 2 instead.

**Comment by alex-konovalov** [comment]
I still can not reproduce the problem in FR's issue tracker :(

**Comment by alex-konovalov** [comment]
There must be some package triggering it. The difference between here and there is that THIS setup for Travis CI only builds several selected packages.

**Comment by fingolfin** [comment]
@alex-konovalov `START_TEST` sets the assertion level to 2, which is the cause of the problem. Hence my suggestion to set it to 0 or 1 instead.

**Comment by alex-konovalov** [comment]
@fingolfin I did not understand that that was a suggestion for an alternative fix - thought of it as a way to reproduce the problem. Now I see what do you mean.

**Comment by fingolfin** [comment]
I took the liberty of rebasing this.

**Comment by fingolfin** [comment]
There is no problem with `fr` anymore in the new PackageDistribution tests, so we can close this

**Pull request closed without merging**
